# Generated by Django 6.1.1 on 2026-09-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
    ]
