# Generated by Django 6.1.1 on 2026-09-22 04:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directores', '0001_initial'),
        ('generos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('pais', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('upc', models.CharField(max_length=20, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion', models.DurationField(help_text='Formato: HH:MM:SS como 01:15:00')),
                ('estrenada', models.BooleanField(default=True)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directores.director')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generos.genero')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_interno', models.CharField(max_length=50)),
                ('disponible', models.BooleanField(default=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.pelicula')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
