# Generated by Django 6.1.1 on 2026-09-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
